valuesFilePath: ./values.yml

pipelines:
  - name: petclinic_basic
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          autoPublishBuildInfo: true
          inputResources:
            - name: mvn_source_repo
          outputResources:
            - name: pc_build_info
          integrations:
            - name: {{ .Values.artifactory }}
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName:  {{ .Values.artifactoryUrl }}/{{ .Values.dockerRepo }}/{{ .Values.imageName }}
          dockerImageTag: ${run_number}
          inputSteps:
            - name: mvn_build_step
          inputResources:
            - name: mvn_source_repo
            - name: mvn_fileSpec
            - name: pc_build_info
          integrations:
            - name: {{ .Values.artifactory }}
        execution:
          onStart:
            - ls -ltra
            - ls -ltra dependencyState/resources/mvn_source_repo
            - echo "spring-petclinic-2.2.0.BUILD-${run_number}.jar"