valuesFilePath: ./values.yml

pipelines:
  - name: petclinic_basic
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          resolverSnapshotRepo: {{ .Values.deployerRepo }}
          resolverReleaseRepo: {{ .Values.deployerRepo }}
          autoPublishBuildInfo: true
          inputResources:
            - name: mvn_source_repo
          outputResources:
            - name: pc_build_info
          integrations:
            - name: {{ .Values.artifactory }}
      
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName:  {{ .Values.artifactoryUrl }}/{{ .Values.dockerRepo }}/{{ .Values.imageName }}
          dockerImageTag: ${run_number}
          inputSteps:
            - name: mvn_build_step
          inputResources:
            - name: mvn_source_repo
            - name: mvn_fileSpec
            - name: pc_build_info
          integrations:
            - name: {{ .Values.artifactory }}
      
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_group
          targetRepository: {{ .Values.dockerRepo }}
          integrations:
            - name: {{ .Values.artifactory }}                           
          # inputResources:
          #   - name: pc_build_info
          inputSteps:
            - name: docker_build
 
      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          affinityGroup: docker_group
          inputSteps:
            - name: docker_push
          outputResources:
            - name: pc_build_info